CREATE TABLE IF NOT EXISTS bc_chain (
  id INT NOT NULL AUTO_INCREMENT,
  chain_id INT NOT NULL,
  name VARCHAR(50) NOT NULL,
  native_symbol VARCHAR(20) NOT NULL DEFAULT 'ETH',
  rpc_urls JSON NOT NULL,
  explorer_url VARCHAR(500) NULL,
  status TINYINT NOT NULL DEFAULT 1,
  login_enabled TINYINT NOT NULL DEFAULT 1,
  sort INT NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_bc_chain_chain_id (chain_id)
);
